# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#es:
#  languageCode: es
#  contentDir: content/es
#  title: Vegan Pa'l Susto. 
#  params:
#    description: La primera panadería vegana en Reino Unido!
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
